--
-- PostgreSQL database dump
--

\restrict GIfzJdUn9gmTxcei6mK5pKfYrnauSjA09r0Rbzxv9NaprISE7eRUveCjVVoAlZp

-- Dumped from database version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)
-- Dumped by pg_dump version 18.6 (Ubuntu 18.6-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: car_companies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.car_companies (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.car_companies OWNER TO postgres;

--
-- Name: car_companies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.car_companies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_companies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: car_origins; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.car_origins (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.car_origins OWNER TO postgres;

--
-- Name: car_origins_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.car_origins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.car_origins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cars; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cars (
    id bigint NOT NULL,
    model text NOT NULL,
    year integer NOT NULL,
    price numeric(12,2) NOT NULL,
    company_id bigint NOT NULL,
    origin_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT cars_price_check CHECK ((price >= (0)::numeric)),
    CONSTRAINT cars_year_check CHECK (((year >= 1886) AND (year <= 2100)))
);


ALTER TABLE public.cars OWNER TO postgres;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deepseek; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deepseek (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text
);


ALTER TABLE public.deepseek OWNER TO postgres;

--
-- Name: deepseek_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deepseek ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deepseek_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: car_companies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.car_companies (id, name, created_at) FROM stdin;
1	Mercedes-Benz	2026-10-04 19:48:35.050934+13
2	Kia	2026-10-04 19:48:35.050934+13
3	Ford	2026-10-04 19:48:35.050934+13
4	Toyota	2026-10-04 19:48:35.050934+13
5	BMW	2026-10-04 19:48:35.050934+13
6	Hyundai	2026-10-04 19:48:35.050934+13
7	Volkswagen	2026-10-04 19:48:35.050934+13
\.


--
-- Data for Name: car_origins; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.car_origins (id, name, created_at) FROM stdin;
1	Germany	2026-10-04 19:48:35.053879+13
2	South Korea	2026-10-04 19:48:35.053879+13
3	United States	2026-10-04 19:48:35.053879+13
4	Japan	2026-10-04 19:48:35.053879+13
\.


--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cars (id, model, year, price, company_id, origin_id, created_at) FROM stdin;
1	Golf	2021	27000.00	7	1	2026-10-04 19:48:35.056558+13
2	3 Series	2022	42000.00	5	1	2026-10-04 19:48:35.056558+13
3	C-Class	2023	45000.00	1	1	2026-10-04 19:48:35.056558+13
4	Tucson	2023	31000.00	6	2	2026-10-04 19:48:35.056558+13
5	Sportage	2022	28000.00	2	2	2026-10-04 19:48:35.056558+13
6	Mustang	2021	55000.00	3	3	2026-10-04 19:48:35.056558+13
7	Corolla	2023	24000.00	4	4	2026-10-04 19:48:35.056558+13
\.


--
-- Data for Name: deepseek; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deepseek (id, created_at, name) FROM stdin;
1	2026-10-04 19:44:24.987602+13	row created locally by the agent
\.


--
-- Name: car_companies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.car_companies_id_seq', 14, true);


--
-- Name: car_origins_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.car_origins_id_seq', 8, true);


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cars_id_seq', 8, true);


--
-- Name: deepseek_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deepseek_id_seq', 1, true);


--
-- Name: car_companies car_companies_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_companies
    ADD CONSTRAINT car_companies_name_key UNIQUE (name);


--
-- Name: car_companies car_companies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_companies
    ADD CONSTRAINT car_companies_pkey PRIMARY KEY (id);


--
-- Name: car_origins car_origins_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_origins
    ADD CONSTRAINT car_origins_name_key UNIQUE (name);


--
-- Name: car_origins car_origins_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.car_origins
    ADD CONSTRAINT car_origins_pkey PRIMARY KEY (id);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: deepseek deepseek_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deepseek
    ADD CONSTRAINT deepseek_pkey PRIMARY KEY (id);


--
-- Name: cars_company_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cars_company_id_idx ON public.cars USING btree (company_id);


--
-- Name: cars_origin_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX cars_origin_id_idx ON public.cars USING btree (origin_id);


--
-- Name: cars cars_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.car_companies(id) ON DELETE RESTRICT;


--
-- Name: cars cars_origin_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_origin_id_fkey FOREIGN KEY (origin_id) REFERENCES public.car_origins(id) ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict GIfzJdUn9gmTxcei6mK5pKfYrnauSjA09r0Rbzxv9NaprISE7eRUveCjVVoAlZp

