-- =====================================================================
--  cars / car_companies / car_origins
--  Target database: deepseek (local PostgreSQL 18)
--
--  Normalised design: the car's maker and its country of origin each live
--  in their own table, so `cars` carries two foreign keys.
--
--  This file is idempotent — safe to run more than once.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Lookup table: car companies (the maker)
-- ---------------------------------------------------------------------
create table if not exists public.car_companies (
  id         bigint generated by default as identity primary key,
  name       text        not null unique,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2. Lookup table: countries of origin
-- ---------------------------------------------------------------------
create table if not exists public.car_origins (
  id         bigint generated by default as identity primary key,
  name       text        not null unique,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 3. The car itself — two foreign keys, one to each lookup table
-- ---------------------------------------------------------------------
create table if not exists public.cars (
  id         bigint generated by default as identity primary key,
  model      text        not null,
  year       integer     not null check (year between 1886 and 2100),
  price      numeric(12,2) not null check (price >= 0),
  company_id bigint      not null references public.car_companies (id) on delete restrict,
  origin_id  bigint      not null references public.car_origins   (id) on delete restrict,
  created_at timestamptz not null default now()
);

-- Postgres does not index foreign keys automatically; joins on these
-- columns would otherwise force sequential scans.
create index if not exists cars_company_id_idx on public.cars (company_id);
create index if not exists cars_origin_id_idx  on public.cars (origin_id);

-- =====================================================================
-- 4. Seed data
-- =====================================================================

insert into public.car_companies (name) values
  ('Mercedes-Benz'),
  ('Kia'),
  ('Ford'),
  ('Toyota'),
  ('BMW'),
  ('Hyundai'),
  ('Volkswagen')
on conflict (name) do nothing;

insert into public.car_origins (name) values
  ('Germany'),
  ('South Korea'),
  ('United States'),
  ('Japan')
on conflict (name) do nothing;

-- Seed cars only when the table is empty, so re-running doesn't duplicate.
do $$
begin
  if not exists (select 1 from public.cars) then
    insert into public.cars (model, year, price, company_id, origin_id)
    select v.model, v.year, v.price, c.id, o.id
    from (values
      ('C-Class',  2023, 45000.00, 'Mercedes-Benz', 'Germany'),
      ('Sportage', 2022, 28000.00, 'Kia',           'South Korea'),
      ('Mustang',  2021, 55000.00, 'Ford',          'United States'),
      ('Corolla',  2023, 24000.00, 'Toyota',        'Japan'),
      ('3 Series', 2022, 42000.00, 'BMW',           'Germany'),
      ('Tucson',   2023, 31000.00, 'Hyundai',       'South Korea'),
      ('Golf',     2021, 27000.00, 'Volkswagen',    'Germany')
    ) as v(model, year, price, company, origin)
    join public.car_companies c on c.name = v.company
    join public.car_origins   o on o.name = v.origin;
  end if;
end $$;
